name: Build and Publish to Package manager

on:
  push:
    branches:
    - main
    
jobs:
  build-change-logs:
    runs-on: ubuntu-latest
    name: Build change logs
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use pnpm from package.json
        uses: pnpm/action-setup@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build business change logs
        run: |
          npx changeset version
          echo "RELEASE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
          cat ./CHANGELOG.md >> $GITHUB_STEP_SUMMARY

  publish-package:
    name: Publish package to Github
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Publish
        run: |
          echo Published