on:
  push:
    branches:
    - main
    
jobs:
  echo-something:
    runs-on: ubuntu-latest
    name: Echo Something
    steps:
      - name: Echo
        run: |
          echo "Hello world"

  publish:
    runs-on: ubuntu-latest
    name: Publish package
    environment: production
    steps:
      - name: Publish
        run: |
          echo "Published"
